version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    hostname: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: email 
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${EMAIL_FROM}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${EMAIL_TO}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${EMAIL_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${APP_PASSWORD}
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2 
    networks:
      - frontend
      - backend
    command: --debug --cleanup --schedule "0 0 1 * * *"

networks:
  frontend:
    external: true
  backend:
    external: true